Nicholas-Parise/4P02-course-project

- wishify/src/components/SettingsItem.jsx
- wishify/src/login.css
- wishify/src/pages/Profile.jsx
- wishify/src/pages/auth/Login.jsx
- wishify/src/pages/auth/Register.jsx
- wishify/src/profile.css
- wishify/src/register.css
-Added authentication functionality (connected to backend) to allow register and login
-Added input validation
-Changes and visual improvements made to profile settings
> Authentication implementation, profile settings improvements

- wishify/src/login.css
- wishify/src/pages/auth/Login.jsx
- wishify/src/pages/auth/Register.jsx
- wishify/src/register.css
Completed authorization feedback and redirects as necessary in register and login pages. Success or error messages are displayed appropriately. Automatic redirect to home page upon successful login implemented. Submit button disabled while server is authenticating.
> Completed auth feedback and redirects

- wishify/src/home.css
- wishify/src/pages/Home.jsx
Home page created. Added placeholders for Wishlists and Events, as well as links to their respective pages.
> Home Update 1.0

- wishify/src/App.jsx
- wishify/src/components/Navbar.tsx
- wishify/src/components/ProtectedRoutes.tsx
- wishify/src/pages/Event.jsx
- wishify/src/pages/Events.jsx
- wishify/src/pages/Home.jsx
- wishify/src/pages/Index.jsx
- wishify/src/pages/Landing.jsx
- wishify/src/pages/NoPage.jsx
- wishify/src/pages/Profile.jsx
- wishify/src/pages/Wishlist.tsx
- wishify/src/pages/Wishlists.jsx
- wishify/src/pages/auth/Login.jsx
- wishify/src/pages/auth/Register.jsx
- wishify/src/utils/isLoggedIn.tsx
Changed back to only using a single Navbar that will render dynamically depending if the user is logged in. 
It didn't seem very clean to have the 2 Navbars hard coded on every page, because if someone went back to the landing page despite being logged in, they would assume they were logged out, even though they were not.
Going to the base route "/" (index) will now dynamically render the landing page if the user is **not** logged in, and it will render the home page if they **are** logged in.
Going to any route that has dynamic content like events, wishlists, profile, etc, will now redirect to the login page if the user is not logged in. These are the routes under the \<ProtectedRoutes/\> Route in App.jsx. I took the code from a YouTube tutorial.
The isLoggedIn() utils function should be …
> Major Refactoring of Navbar and Routes

- wishify/src/components/CreateButton.tsx
- wishify/src/components/CreateItemDialog.tsx
- wishify/src/components/Navbarlanding/landingheader.css
- wishify/src/components/ProfileSettingModals/DeleteAccountModal.jsx
- wishify/src/components/ProfileSettingModals/EditBioModal.jsx
- wishify/src/components/ProfileSettingModals/EditDisplayNameModal.jsx
- wishify/src/components/ProfileSettingModals/EditEmailModal.jsx
- wishify/src/components/ProfileSettingModals/EditPasswordModal.jsx
- wishify/src/components/Thumbnail.tsx
- wishify/src/components/WishlistHeader.tsx
- wishify/src/components/WishlistItemEntry.tsx
- wishify/src/home.css
- wishify/src/pages/Events.jsx
- wishify/src/pages/Home.jsx
- wishify/src/pages/Profile.jsx
- wishify/src/pages/Wishlist.tsx
- wishify/src/pages/Wishlists.tsx
- wishify/src/profile.css
The vast majority of CSS changes are in here but not all.
> Added Justin's CSS changes without the code refactors

- wishify/src/components/DeleteItemModal.tsx
- wishify/src/components/WishlistItemEntry.tsx
- wishify/src/pages/Wishlist.tsx
I copied one of Anthony's modals and made it for deleting an item. The delete button is a trash bin icon on an item's drag and drop list entry.
> Adding delete item feature

- wishify/src/components/LikesSettingsItem.jsx
- wishify/src/components/ProfileSettingModals/AddLikesModal.jsx
- wishify/src/components/ProfileSettingModals/EditPasswordModal.jsx
- wishify/src/pages/Profile.jsx
All profile settings functionality and communication with backend finalized
> Finalized profile settings functionality and backend connections

- package-lock.json
- wishify/src/pages/Home.jsx
Connected the wishlists, events, and user profile on the home page to the backend.
> Home Page Backend Connection

- backend/pytest/tests/conftest.py
- backend/pytest/tests/test_events.py
- backend/pytest/tests/test_wishlists.py
- wishify/src/components/TestModuleAccordian.tsx
- wishify/src/pages/Status.tsx
- Fixed typo in Status page that cause the wrong colours to be used.
- Fixed pytest cleanup fixtures to properly take in the data they require.
- Changed order of pytest fixtures so account_cleanup is the last cleanup fixture
> fixing bugs with status page and pytests

- wishify/package-lock.json
- wishify/src/App.jsx
- wishify/src/components/Navbar.tsx
- wishify/src/components/ProfileMenu.tsx
- wishify/src/pages/Ideas.tsx
- wishify/src/pages/Wishlist.tsx
- wishify/src/pages/Wishlists.tsx
- wishify/src/types/types.ts
-made sidebar profile menu take from backend for name and email 
-fixed wishlists page to put shared wishlists in the right spot
> -added ideas page with placeholder data

- backend/pytest/tests/conftest.py
- backend/pytest/tests/test_contributions.py
- backend/pytest/tests/test_events.py
- backend/pytest/tests/test_items.py
- backend/pytest/tests/test_users.py
- backend/pytest/tests/test_wishlists.py
Added tests for
- Items
- Contributions
- Token checks when deleting wishlists and events
- Password checks when deleting a user
> Adding more tests

- backend/pytest/tests/test_auth.py
forgot this in the last merge, oops
> creating accounts now disables notifications

- wishify/src/components/ProfileSettingModals/FirstSetupModal.jsx
- wishify/src/components/ProfileSettingModals/index.js
- wishify/src/pages/Profile.jsx
- wishify/src/pages/PublicProfile.jsx
- wishify/src/profile.css
First time setup component still needs some work. Also implemented categories tests and minor improvements to public profile.
> Implemented component for first time setup

- wishify/src/components/ProfileSettingModals/FirstSetupModal.jsx
- wishify/src/pages/Home.jsx
First setup fully implemented on homepage. Works fine for existing users. Still needs styling.
> Finished first setup implementation

- wishify/src/components/CreateItemDialog.tsx
- wishify/src/components/LinkEventModal.tsx
- wishify/src/components/MemberDialog.tsx
- wishify/src/components/ProfileMenu.tsx
- wishify/src/components/WishlistHeader.tsx
- wishify/src/components/WishlistItemEntry.tsx
- wishify/src/pages/Wishlist.tsx
- wishify/src/types/types.ts
- Wishlist now respect the blind status
- You can toggle ownership and blind status
- Member view now shows profile picture
- You can toggle notifications for the wishlist
- You can link an event to a wishlist if there isn't one already linked
> Individual Wishlist Updates

- wishify/src/components/Thumbnail.tsx
- wishify/src/pages/Wishlists.tsx
- wishify/src/types/types.ts
-display creators of wishlists
-fixed logic of shared wishlists
-added crown icon to show ownership permissions
> Owned wishlists

- wishify/src/components/ProfileSettingModals/EditPictureModal.jsx
- wishify/src/pages/Profile.jsx
Want to test after it's merged
> Upload profile picture funtionality, not working on localhost

- wishify/src/components/ProfileSettingModals/EditPictureModal.jsx
Quick fix... backend expecting 'picture' not 'image'
> Fixed error, can successfully upload pictures now

- wishify/src/Landing.css
- wishify/src/components/AddIdeaModal.tsx
- wishify/src/components/CreateButton.tsx
- wishify/src/components/CreateWishlistModal.tsx
- wishify/src/components/Loading.css
- wishify/src/components/Loading.jsx
- wishify/src/components/PopularItems.css
- wishify/src/components/PopularItems.jsx
- wishify/src/components/ShareEventModal.tsx
- wishify/src/components/Thumbnail.tsx
- wishify/src/pages/Event.jsx
- wishify/src/pages/Events.tsx
- wishify/src/pages/Ideas.tsx
- wishify/src/pages/Wishlists.tsx
- wishify/src/types/types.ts
- share and member button added to event page
- this branch has also merged from my other branches [ideas-page,pro-features/stephen,event-wishlist-homepages]
> Individual event

- wishify/src/Landing.css
- wishify/src/components/EventMemberDialog.tsx
- wishify/src/components/PopularItems.css
- wishify/src/components/PopularItems.jsx
- wishify/src/components/ShareEventModal.tsx
- wishify/src/pages/Event.jsx
- wishify/src/pages/Events.tsx
- wishify/src/pages/Ideas.tsx
- wishify/src/pages/Landing.jsx
- wishify/src/types/types.ts
some small fixes for event sharing and ideas page
> Ideas page

- wishify/package.json
- wishify/src/App.jsx
- wishify/src/components/MemberDialog.tsx
- wishify/src/components/Navbar.tsx
- wishify/src/components/NotificationEntry.tsx
- wishify/src/components/ProfileMenu.css
- wishify/src/components/ProfileMenu.tsx
- wishify/src/components/ShareWishlistModal.tsx
- wishify/src/components/WishlistHeader.tsx
- wishify/src/components/landingheader.css
- wishify/src/pages/Home.jsx
- wishify/src/types/types.ts
Navbar.tsx pulls notifications every 25 seconds and will make a toast if there is at least 1 that isn't read.
Clicking on the toast will open the profile menu, and the unread notifications will be highlighted, but after the refresh they will lose the highlight.
> added notifications to the profile menu

- wishify/package-lock.json
- wishify/src/Landing.css
- wishify/src/components/ProfileMenu.css
- wishify/src/components/ProfileMenu.tsx
- wishify/src/pages/Landing.jsx
This is the finalized Landing Page
> Landing Page - Final

- wishify/src/App.jsx
- wishify/src/components/LikesSettingsItem.jsx
- wishify/src/components/ProfileSettingModals/AddLikesModal.jsx
- wishify/src/components/ProfileSettingModals/DeleteAccountModal.jsx
- wishify/src/components/ProfileSettingModals/EditBioModal.jsx
- wishify/src/components/ProfileSettingModals/EditDisplayNameModal.jsx
- wishify/src/components/ProfileSettingModals/EditEmailModal.jsx
- wishify/src/components/ProfileSettingModals/EditPasswordModal.jsx
- wishify/src/components/ProfileSettingModals/EditPictureModal.jsx
- wishify/src/components/SettingsItem.jsx
- wishify/src/pages/Profile.jsx
- wishify/src/pages/PublicProfile.jsx
- wishify/src/pages/auth/Login.jsx
- wishify/src/pages/auth/Register.jsx
- wishify/src/profile.css
CSS design tweaks with mobile responsiveness to profile settings and it's modals
> Profile Settings CSS

- wishify/src/App.css
- wishify/src/components/AddIdeaModal.tsx
- wishify/src/components/PopularItems.css
- wishify/src/components/PopularItems.jsx
- wishify/src/pages/Ideas.tsx
All CSS changes made for the ideas page to make it look good for both mobile as well as webapplication! Might look like a lot of changes! but most of it is CSS changes and changes to indentation!
> Final Ideas Page

- wishify/src/components/ShareEventModal.tsx
- wishify/src/pages/Event.jsx
All CSS changes and layout of the event page has been completed
> Final Event Page completed

- wishify/src/Landing.css
- wishify/src/components/CreateButton.tsx
- wishify/src/components/Navbar.tsx
- wishify/src/components/Thumbnail.tsx
- wishify/src/home.css
- wishify/src/pages/Event.jsx
- wishify/src/pages/Events.tsx
- wishify/src/pages/Home.jsx
- wishify/src/pages/Wishlists.tsx
All changes to CSS for Homepage events page and Wishlists Page has been updated and finalised
> All CSS changes for Home page Events page and CSS

- wishify/src/pages/Profile.jsx
- wishify/src/profile.css
Profile settings no longer render email and change password if oauth user
> profile settings conditional rendering

- wishify/src/components/HelpMenu.css
- wishify/src/components/HelpMenu.tsx
Added more descriptions to the help menu. The help menu was also spruced up a bit.
> Help Menu Update

- wishify/src/components/LinkEventModal.tsx
- wishify/src/components/WishlistHeader.tsx
- wishify/src/components/WishlistItemEntry.tsx
- wishify/src/pages/Wishlist.tsx
- wishify/src/types/types.ts
Updated the contribution section and you can now marked as purchased.
You can now unlink events from the wishlist page
> updated contribution note section

- wishify/src/components/ProfileSettingModals/DeleteAccountModal.jsx
- wishify/src/components/ProfileSettingModals/EditPictureModal.jsx
- wishify/src/components/ProfileSettingModals/FirstSetupModal.jsx
- wishify/src/pages/Profile.jsx
- wishify/src/pages/auth/Register.jsx
- After successful registration, page auto-redirects to Login
- Password hint disappears upon valid password value
- Avatar default image changed from 'P' to a person icon
- Added warning for PRO users upon account deletion
- Max character limit set to 300 for first setup bio input (to match profile settings)
- Max character limit for Display Name adjusted to 30 on Register form (to match profile settings)
> Successful signup auto-redirect, other small improvements.

- wishify/src/App.jsx
- wishify/src/components/CreateButton.tsx
- wishify/src/components/ProfileMenu.tsx
- wishify/src/components/Thumbnail.tsx
- wishify/src/pages/Event.jsx
- wishify/src/pages/Events.tsx
- wishify/src/pages/Wishlists.tsx
> Final CSS Changes

- wishify/src/App.jsx
- wishify/src/components/CreateEventModal.tsx
- wishify/src/components/CreateWishlistModal.tsx
- wishify/src/components/Navbar.tsx
- wishify/src/components/NotificationEntry.tsx
- wishify/src/components/ProfileMenu.tsx
- wishify/src/components/Thumbnail.tsx
- wishify/src/components/WishlistHeader.tsx
- wishify/src/pages/Event.jsx
- wishify/src/pages/Profile.jsx
- Notifications are marked read when you click on them
- Event page wishlists now use the share_token links to easily add them as a member to the wishlist so they can make contributions
- Updated header on Wishlist page
- Wishlist deadlines now use a DateTimePicker and not just a DatePicker
- Creating a wishlist on the wishlists page now updates the state correctly without needing to refresh
- Deleting an account now does setIsLoggedIn(false)
> Various changes
